/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb4aa",
        "bg-primary": "#0F1117",
        "on-primary-fixed-variant": "#00513f",
        "status-success": "#5FD3BC",
        "secondary-container": "#3f2bb8",
        "on-secondary": "#2700a1",
        "accent-purple": "#7C6FF7",
        "on-surface-variant": "#bacac2",
        "text-tertiary": "#717880",
        "surface-tint": "#28dfb5",
        "surface-container-highest": "#313444",
        "secondary-fixed-dim": "#c6c0ff",
        "background": "#0f1321",
        "primary-fixed-dim": "#28dfb5",
        "surface-container": "#1c1f2e",
        "inverse-surface": "#e0e1f6",
        "outline": "#85948d",
        "error-container": "#93000a",
        "outline-variant": "#3b4a44",
        "primary-fixed": "#55fcd0",
        "on-background": "#e0e1f6",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#b3acff",
        "inverse-on-surface": "#2d303f",
        "status-error": "#FF6B5B",
        "on-tertiary-fixed-variant": "#8c1712",
        "error": "#ffb4ab",
        "accent-teal": "#00D4AA",
        "text-secondary": "#A8AEB8",
        "tertiary-fixed": "#ffdad5",
        "bg-tertiary": "#16191F",
        "surface-container-lowest": "#0a0d1c",
        "on-primary-fixed": "#002118",
        "secondary-fixed": "#e4dfff",
        "primary-container": "#00d4aa",
        "on-primary": "#00382b",
        "on-surface": "#e0e1f6",
        "on-secondary-fixed-variant": "#3f2bb8",
        "inverse-primary": "#006b55",
        "on-error": "#690005",
        "bg-secondary": "#1C1F2E",
        "on-tertiary-fixed": "#410001",
        "primary": "#46f1c5",
        "surface-bright": "#353848",
        "surface": "#0f1321",
        "on-secondary-fixed": "#150066",
        "on-tertiary-container": "#931c16",
        "surface-variant": "#313444",
        "surface-container-low": "#181b2a",
        "on-primary-container": "#005643",
        "surface-container-high": "#262939",
        "tertiary-container": "#ffa498",
        "surface-dim": "#0f1321",
        "secondary": "#c6c0ff",
        "text-primary": "#E8EAED",
        "tertiary": "#ffccc4",
        "on-tertiary": "#690003",
        "status-warning": "#FFB400"
      },
      spacing: {
        "xxl": "48px",
        "lg": "24px",
        "sm": "12px",
        "base": "4px",
        "margin-desktop": "32px",
        "xs": "8px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "md": "16px",
        "xl": "32px"
      },
      fontFamily: {
        "headline-h1-mobile": ["Inter", "sans-serif"],
        "body-rg": ["Inter", "sans-serif"],
        "headline-h2": ["Inter", "sans-serif"],
        "headline-h3": ["Inter", "sans-serif"],
        "headline-h1": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "data-mono": ["Fira Code", "monospace"],
        "hero-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-h1-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-rg": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-h2": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-h3": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-h1": ["36px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "data-mono": ["13px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "hero-lg": ["48px", { "lineHeight": "1.1", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
